Cedar/Proto_IKE: fix too many arguments to function 'NewBuf'
This commit fixes the following error:

```
Proto_IKE.c: In function ‘ProcIkeQuickModePacketRecv’:
Proto_IKE.c:2362:146: error: too many arguments to function ‘NewBuf’; expected 0, have 2
 2362 |                                                                                                                         ipsec_sa_sc->SharedKey = NewBuf(shared_key, shared_key_size);
      |                                                                                                                                                  ^~~~~~ ~~~~~~~~~~
In file included from ../../src/Mayaqua/Mayaqua.h:338,
                 from CedarPch.h:115,
                 from IPsec_IKE.c:105:
../../src/Mayaqua/Memory.h:303:6: note: declared here
  303 | BUF *NewBuf();
      |      ^~~~~~
Proto_IKE.c:2363:146: error: too many arguments to function ‘NewBuf’; expected 0, have 2
 2363 |                                                                                                                         ipsec_sa_cs->SharedKey = NewBuf(shared_key, shared_key_size);
      |                                                                                                                                                  ^~~~~~ ~~~~~~~~~~
```

The function `NewBuf` is defined without arguments. Replace it in favour
of `NewBufFromMemory` that copy the content of the pointer into a new
buffer.